Repository lazybird/django-solo, pull requests merged in 2024-10, with the labels that each got.

#140 Disambiguate cache key for similarly named models
  CHANGES
  solo/models.py
  solo/tests/settings.py
  solo/tests/testapp2/__init__.py
  solo/tests/testapp2/models.py
  solo/tests/tests.py
Labels: bug

#141 Update supported Python and Django versions
  .github/workflows/python.yml
  CHANGES
  pyproject.toml
  solo/models.py
  tox.ini
Labels: dependencies

#138 Fix error handling in template tag
  solo/templatetags/solo_tags.py
  solo/tests/tests.py
Labels: bug

#142 Update CHANGES for #138
  CHANGES
Labels: documentation

#143 Simplify default_app_config after dropping support for Django <3.2
  solo/__init__.py
Labels: refactor
